# Generated by Django 4.0.4 on 2022-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='images_file',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
