# Generated by Django 4.0.4 on 2022-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemUser',
            new_name='CustomSystemUser',
        ),
    ]
