# Generated by Django 4.1a1 on 2022-06-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_query_app', '0002_publication_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='publication',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_query_app.reporter'),
        ),
    ]
