# Generated by Django 4.0.4 on 2022-05-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employees_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='EMPLOYEE',
        ),
    ]
